### PR TITLE
Make Gulpfile generic

### PR DESCRIPTION
**Pull request by quis**
This copies the Gulpfile from the suppliers app, which is now generic, and makes the necessary changes to the setup of this app so that it works.

### CODE REVIEW

**Comment by TheDoubleK** [comment]
I have a feeling that the gulpfile change in the suppliers app may have caused the app to break in preview (e.g. see: https://preview.development.digitalmarketplace.service.gov.uk/suppliers/services).  Let's hold off merging this until we get the supplier app fixed and find if there is a problem with the generic version.

**Comment by allait** [comment]
Is this ok to merge? Admin app is currently broken since there was a merge after the new AWS stuff went out.

**Comment by quis** [comment]
@allait I've assigned it to @tombye so he can check that the comments he left on the supplier Gulpfile have also been addressed in this app.

**Comment by tombye** [comment]
:+1:

**Pull request merged**
