### PR TITLE
Add coverage and requirements

### PR DESCRIPTION
**Pull request by quis**

### CODE REVIEW

**Comment by allait** [comment]
Admin app is still using `nosetests`, I don't think it recognises `--cov` arguments. We could try replacing it with `py.test` in `scripts/run_tests.py` to see if that works out of the box.

**Comment by quis** [comment]
@allait edc8e22 
> Also switches from Nosetests to Pytest, because Nose doesn’t recognise `--cov` arguments.

**Comment by quis** [comment]
94.098% :tada:

**Comment by TheDoubleK** [comment]
Nice coverage.

**Comment by allait** [comment]
:+1:

**Pull request merged**
