### PR TITLE
Skeleton admin app

### PR DESCRIPTION
**Pull request by TheDoubleK**
This adds a skeleton Flask app that has:
1. a home page where you can submit a service ID that you want to edit
2. an 'edit service' page that loads the service data from the API and display a few key fields (name, supplier, id)

Needs styling, but the (very) basics are here.

### CODE REVIEW

**Comment by quis** [comment]
Learnt the basics of Flask and Blueprints this morning. This all looks good to me, unless you think someone with more Python knowledge should have a review too?

**Comment by TheDoubleK** [comment]
I think it's small enough and early enough on that we build on this and fix it up as we go.  It probably needs a test in there.  I can add one on this branch before you merge if you like, or just merge now and I promise to add a test as the next thing I do :)

**Comment by quis** [comment]
Add the test on this branch I reckon.

**Comment by TheDoubleK** [comment]
Tests and README added.

**Comment by TheDoubleK** [comment]
Should work now...

**Comment by quis** [comment]
LGTM :+1: tests pass locally, preparing to merge…

**Pull request merged**
