### PR TITLE
Update utils version to wrap errors from all third party services

### PR DESCRIPTION
**Pull request by CrystalPea**
Connected to this pull request: https://github.com/alphagov/digitalmarketplace-utils/pull/393/files

### CODE REVIEW

**Comment by katstevens** [comment]
I'm pretty sure we don't actually use Mandrill in the Admin. There is a more recent utils version (36.12.0) that includes Notify and Mailchimp logging too - shall we pull that one in instead?

**Comment by samuelhwilliams** [comment]
Yessss please 👍

**Comment by samuelhwilliams** [comment]
This PR still says 36.10.1 - think you might need to push the update :)

**Comment by CrystalPea** [comment]
@samuelhwilliams you are right, I forgot to `git add` when amending the commit, whoops 😳

**Pull request merged**
