### PR TITLE
Fix disappearing fields bug

### PR DESCRIPTION
**Pull request by quis**
Brings in https://github.com/alphagov/digitalmarketplace-utils/pull/74 as well as some other fixes to the utils.

This fixes a bug where filtering of the content persisted between requests, causing some fields which should have been shown to start disappearing (terminationCost was the example found by the smoke tests).

### CODE REVIEW

**Comment by allait** [comment]
Could we add a test for the scenario that shows how the issue occurred? Something like:

1. Request a SaaS service
2. Check that terminationCost is not shown
3. Request SCS service
4. Check that terminationCost is shown.

**Comment by quis** [comment]
@allait Turned your `<ol>` into code: b0044d1

**Comment by allait** [comment]
@quis :+1: It's good to merge, just needs a rebase.

**Comment by quis** [comment]
@allait Rebased

**Pull request merged**
